name: Sync Fork

on:
  schedule:
    - cron: '53 * * * *' 
  workflow_dispatch: # on button click


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Sync to Upstream Repository
        uses: rovast/sync-upstream-repo@v0.0.1
        with: 
          upstream_repo: https://github.com/carolmanderson/synctest
          upstream_branch: main
          downstream_branch: dev
          token: ${{ secrets.PAT_TOKEN }}
